In [20]:
import torch
import torch.nn as nn
import numpy as np

In [21]:
a = torch.randn(32, 100, 1)  
print(a.size())
m = nn.Conv1d(100, 100, 1) 
out = m(a)
print(out.size())
print(m)

torch.Size([32, 100, 1])
torch.Size([32, 100, 1])
Conv1d(100, 100, kernel_size=(1,), stride=(1,))


In [75]:
batch_size = 1
length = 10
in_channels = 1
out_channels1 = 2
out_channels2 = 4
kernel_size = 3
# (N, C_in, L)
a = torch.Tensor(np.arange(0, length*batch_size*in_channels).reshape(batch_size, in_channels, length))
print(a)
print('a shape: {}'.format(a.shape))
m = nn.Conv1d(in_channels, out_channels, kernel_size, bias=False)
nn.init.constant_(m.weight, 1)
nn.init.constant_(m.weight[0], 0.5)
print('m: {}'.format(m))
print('m shape: {}'.format(m.weight.shape))
print(m.weight)
with torch.no_grad():
    out = m(a)
print('out: {}'.format(out.shape))
print(out.size())
print(out)

tensor([[[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]])
a shape: torch.Size([1, 1, 10])
m: Conv1d(1, 2, kernel_size=(3,), stride=(1,), bias=False)
m shape: torch.Size([2, 1, 3])
Parameter containing:
tensor([[[0.5000, 0.5000, 0.5000]],

        [[1.0000, 1.0000, 1.0000]]], requires_grad=True)
out: torch.Size([1, 2, 8])
torch.Size([1, 2, 8])
tensor([[[ 1.5000,  3.0000,  4.5000,  6.0000,  7.5000,  9.0000, 10.5000,
          12.0000],
         [ 3.0000,  6.0000,  9.0000, 12.0000, 15.0000, 18.0000, 21.0000,
          24.0000]]])


In [70]:
batch_size = 1
height = 3 
width = 3
conv1_in_channels = 2
conv1_out_channels = 2
conv2_out_channels = 2
kernel_size = 2
# (N, C_in, H, W) is shape of all tensors. (batch_size, channels, height, width)
input = torch.Tensor(np.arange(0, batch_size*height*width*in_channels).reshape(batch_size, in_channels, height, width))
conv1 = nn.Conv2d(in_channels, conv1_out_channels, kernel_size, bias=False) # no bias to make calculations easier
# set the weights of the convolutions to make the convolutions easier to follow
nn.init.constant_(conv1.weight[0][0], 0.25)
nn.init.constant_(conv1.weight[0][1], 0.5)
nn.init.constant_(conv1.weight[1][0], 1) 
nn.init.constant_(conv1.weight[1][1], 2) 
out1 = conv1(input) # compute the convolution

conv2 = nn.Conv2d(conv1_out_channels, conv2_out_channels, kernel_size, bias=False)
nn.init.constant_(conv2.weight[0][0], 0.25)
nn.init.constant_(conv2.weight[0][1], 0.5)
nn.init.constant_(conv2.weight[1][0], 1) 
nn.init.constant_(conv2.weight[1][1], 2) 
out2 = conv2(out1) # compute the convolution

for tensor, name in zip([input, conv1.weight, out1, conv2.weight, out2], ['input', 'conv1', 'out1', 'conv2', 'out2']):
    print('{}: {}'.format(name, tensor))
    print('{} shape: {}'.format(name, tensor.shape))
          
          
          

input: tensor([[[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.]],

         [[ 9., 10., 11.],
          [12., 13., 14.],
          [15., 16., 17.]]]])
input shape: torch.Size([1, 2, 3, 3])
conv1: Parameter containing:
tensor([[[[0.2500, 0.2500],
          [0.2500, 0.2500]],

         [[0.5000, 0.5000],
          [0.5000, 0.5000]]],


        [[[1.0000, 1.0000],
          [1.0000, 1.0000]],

         [[2.0000, 2.0000],
          [2.0000, 2.0000]]]], requires_grad=True)
conv1 shape: torch.Size([2, 2, 2, 2])
out1: tensor([[[[ 24.,  27.],
          [ 33.,  36.]],

         [[ 96., 108.],
          [132., 144.]]]], grad_fn=<MkldnnConvolutionBackward>)
out1 shape: torch.Size([1, 2, 2, 2])
conv2: Parameter containing:
tensor([[[[0.2500, 0.2500],
          [0.2500, 0.2500]],

         [[0.5000, 0.5000],
          [0.5000, 0.5000]]],


        [[[1.0000, 1.0000],
          [1.0000, 1.0000]],

         [[2.0000, 2.0000],
          [2.0000, 2.0000]]]], requires_grad=True)
c

In [78]:
batch_size = 1
length = 10
conv1_in_channels = 2
conv1_out_channels = 5
conv2_out_channels = 2
kernel_size = 2
# (N, C_in, H, W) is shape of all tensors. (batch_size, channels, height, width)
input = torch.Tensor(np.arange(0, batch_size*length*in_channels).reshape(batch_size, in_channels, length))
conv1 = nn.Conv1d(in_channels, conv1_out_channels, kernel_size, bias=False) # no bias to make calculations easier
# shape of conv weights is [out_channels, in_channels, kernel_size]
# set the weights of the convolutions to make the convolutions easier to follow
nn.init.constant_(conv1.weight[0], 0.5)
nn.init.constant_(conv1.weight[1], 1) 
out1 = conv1(input) # compute the convolution

conv2 = nn.Conv1d(conv1_out_channels, conv2_out_channels, kernel_size, bias=False)
nn.init.constant_(conv2.weight[0], 0.5)
nn.init.constant_(conv2.weight[1], 1) 
out2 = conv2(out1) # compute the convolution

for tensor, name in zip([input, conv1.weight, out1, conv2.weight, out2], ['input', 'conv1', 'out1', 'conv2', 'out2']):
    print('{}: {}'.format(name, tensor))
    print('{} shape: {}'.format(name, tensor.shape))
          
          
          

input: tensor([[[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]])
input shape: torch.Size([1, 1, 10])
conv1: Parameter containing:
tensor([[[ 0.5000,  0.5000]],

        [[ 1.0000,  1.0000]],

        [[ 0.4770, -0.5338]],

        [[-0.4857,  0.1509]],

        [[-0.1828, -0.6237]]], requires_grad=True)
conv1 shape: torch.Size([5, 1, 2])
out1: tensor([[[ 0.5000,  1.5000,  2.5000,  3.5000,  4.5000,  5.5000,  6.5000,
           7.5000,  8.5000],
         [ 1.0000,  3.0000,  5.0000,  7.0000,  9.0000, 11.0000, 13.0000,
          15.0000, 17.0000],
         [-0.5338, -0.5906, -0.6474, -0.7041, -0.7609, -0.8177, -0.8745,
          -0.9313, -0.9881],
         [ 0.1509, -0.1840, -0.5189, -0.8538, -1.1886, -1.5235, -1.8584,
          -2.1932, -2.5281],
         [-0.6237, -1.4302, -2.2368, -3.0433, -3.8498, -4.6563, -5.4628,
          -6.2693, -7.0759]]], grad_fn=<SqueezeBackward1>)
out1 shape: torch.Size([1, 5, 9])
conv2: Parameter containing:
tensor([[[0.5000, 0.5000],
         [0.5000, 0.5000],
  