In [1]:
import torch
import sys
sys.path.append('/Users/alfordsimon/Python/hypothesis-posing-proving/')
from deep_rl.utilities.data_structures.Config import Config
from bitenvs.reverse_gym_env import ReverseGymEnv
from deep_rl.agents.DQN_agents.DQN_HER import DQN_HER


In [2]:
model_path = '/Users/alfordsimon/Python/hypothesis-posing-proving/dqn/data/reverse_env/models/her_10_3_1_0_(6).pt'

In [3]:
state_dict = torch.load(model_path)

In [4]:
print(state_dict.keys())

odict_keys(['hidden_layers.0.weight', 'hidden_layers.0.bias', 'hidden_layers.1.weight', 'hidden_layers.1.bias', 'output_layers.0.weight', 'output_layers.0.bias'])


In [5]:
config = Config()
str_len = 10
reverse_len = 3
reverse_offset = 1
num_obscured = 0

config.environment = ReverseGymEnv(str_len, reverse_len, reverse_offset,
        num_obscured)
config.seed = 1
config.num_episodes_to_run = 1000
config.show_solution_score = False
config.visualise_individual_results = False
config.visualise_overall_agent_results = True
config.standard_deviation_results = 1.0
config.runs_per_agent = 1
config.use_GPU = False
config.overwrite_existing_results_file = True
config.randomise_random_seed = True
config.seed = 1

config.hyperparameters = {
        'learning_rate': 0.001,
        'batch_size': 128,
        'buffer_size': 100000,
        'epsilon_decay_rate_denominator': 150,
        'discount_rate': 0.999,
        'incremental_td_error': 1e-8,
        'update_every_n_steps': 1,
        'linear_hidden_units': [64, 64],
        'final_layer_activation': None,
#        'y_range': (0, 1),
        'y_range': (-1, str_len),
        'batch_norm': False,
        'gradient_clipping_norm': 5,
        'HER_sample_proportion': 0.8,
        'learning_iterations': 1,
        'clip_rewards': False
}


In [6]:
agent = DQN_HER(config)

TITLE  ReverseEnv: (10, 3, 1, 0)


In [7]:
model = agent.q_network_local

In [8]:
type(model)

deep_rl.nn_builder.pytorch.NN.NN

In [9]:
model.state_dict()

OrderedDict([('hidden_layers.0.weight',
              tensor([[ 0.1152, -0.0987, -0.0433,  ..., -0.0009,  0.1955,  0.0696],
                      [-0.0833, -0.1350, -0.0375,  ..., -0.0372,  0.0957, -0.1039],
                      [ 0.2194, -0.0946,  0.1677,  ..., -0.1493,  0.1362,  0.0694],
                      ...,
                      [-0.0276, -0.1422, -0.0426,  ..., -0.0602, -0.0109, -0.0979],
                      [ 0.0306, -0.1441,  0.0920,  ..., -0.0103,  0.1630,  0.0610],
                      [ 0.0642,  0.0007, -0.0934,  ..., -0.1899,  0.1434, -0.1382]])),
             ('hidden_layers.0.bias',
              tensor([ 0.0029, -0.0003,  0.0383, -0.0131,  0.1160,  0.0307,  0.1603,  0.0483,
                      -0.0028,  0.0317,  0.1490,  0.0337,  0.1575, -0.0212,  0.0019,  0.1879,
                      -0.2111,  0.0223,  0.2042, -0.1122, -0.0412, -0.0135,  0.0737,  0.0845,
                       0.0507,  0.0882, -0.0959,  0.0941, -0.0709,  0.1405, -0.0656, -0.1904,
            

In [10]:
state_dict.keys()

odict_keys(['hidden_layers.0.weight', 'hidden_layers.0.bias', 'hidden_layers.1.weight', 'hidden_layers.1.bias', 'output_layers.0.weight', 'output_layers.0.bias'])

In [13]:
state_dict['hidden_layers.0.weight'][0]

tensor([ 0.0322, -0.7578,  0.0467, -0.8248, -0.0199,  0.3776, -0.0124,  0.5225,
         0.1582,  0.6630, -0.0744,  0.7493, -0.0403,  0.4297, -0.0054, -0.3248,
        -0.0129, -0.5334, -0.1287, -0.6377])

In [53]:
model.load_state_dict(state_dict)

IncompatibleKeys(missing_keys=[], unexpected_keys=[])

In [54]:
model.state_dict()

OrderedDict([('hidden_layers.0.weight',
              tensor([[-0.2084, -0.4238,  0.2642,  ...,  0.0999, -0.0078, -0.1226],
                      [ 0.1094,  0.0145,  0.0641,  ..., -0.0531, -0.0602, -0.9345],
                      [ 0.3353, -0.0599,  0.0954,  ...,  0.3941,  0.2766,  0.5709],
                      ...,
                      [-0.0328, -0.0219, -0.2072,  ..., -0.5513, -0.0165, -0.1559],
                      [-0.4279,  0.4932, -0.0480,  ...,  0.2084, -0.0867,  0.1693],
                      [-0.4155, -0.2256,  0.2310,  ..., -0.0027,  0.4370,  0.2058]])),
             ('hidden_layers.0.bias',
              tensor([-0.0712,  0.1675,  0.0217,  0.1452,  0.1612,  0.2155, -0.0125, -0.0009,
                       0.1048, -0.0018, -0.1719,  0.1087,  0.0129, -0.1081, -0.1134, -0.1516,
                       0.0382,  0.1038,  0.1626, -0.3152,  0.0287,  0.3234,  0.0356, -0.0989,
                       0.0018, -0.0649, -0.0088, -0.0807,  0.0857, -0.2188, -0.0308, -0.1498,
            

In [55]:
agent.run_n_episodes(num_episodes=100)

 Episode 100, Score:  10.00, Max score seen:  2.00, Rolling score:  9.16, Max rolling score seen:  8.62"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" 
DQN-HER did not achieve required score 



TypeError: file must have a 'write' attribute